### PR TITLE
License Cleanups

### PR DESCRIPTION
**Pull request by seriesumei**
This is the first in a set of license clarification and cleanup PRs...

* CC-By-3.0
  * put the plaincode text version in Licenses/
* Update sources and readme for CMFF Templates, re-export as PNG
* Remove Skins/Skin, Splendor by Sezmra as it includes a non-commercial
  clause that is incompatible with AGPL.
* Rename skin directories to a consistent format and include references
* Re-export JPG files as PNG
* Put PNG files into subdirectories

### CODE REVIEW

**Comment by Outworldz** [comment]
"Skin, Splendor by Sezmra " is allowed.  AGPL is commercial, too. Skins are not a part of the AGPL license for the mesh body or scripts.

**Comment by Outworldz** [comment]
Robin Wood templates are not allowed!

From her web site:  All content on this page is © Robin Wood, unless otherwise noted. All rights reserved.
Please do not use it without permission. 
To get permission, write to "chat at robinwood.com", and explain what you intend to use it for.

**Comment by seriesumei** [comment]
Fred, My concern with Sezmra's skin is she does not allow commercial use while the rest of Ruth/Roth (AGPL) does.  I worry that mixing licenses like this is dangerous because now someone who wants to re-package Ruth in-world and add other things to it must know to look (which you should anyway!) and not include Sezmra's skin.  That is the incompatibility with GPL and distribution and specific non-commercial clauses.  I would rather move most of the skins to a separate repo anyway but that is a different conversation...

**Comment by seriesumei** [comment]
I have renamed the skin directories to be consistent and included readme files.  I was thinking about removing the jpg files and including new png exports for at least a handful of variations, thoughts?

**Comment by AdaRadius** [comment]
Yes to png. I have fashionable underwear, leftovers from a contract I did last summer which I don't think I've uploaded. I'll put them together with the Starlight skins and donate them.

**Comment by seriesumei** [comment]
I'm going to stop here, I've re-exported the PSD files to update the XCF files with Gimp 2.10 and replaced JPG with PNG where possible...

**Pull request merged**
