### PR TITLE
Create archive-rc2 branch

### PR DESCRIPTION
**Pull request by seriesumei**
NOTE: This should not be merged into the main branch, once we have an archive-rc2 branch created in RuthAndRoth/Ruth repo we can re-target this PR to that branch.

This creates a new archive-rc2 branch that captures the state of the repository at the point of Shin's last commit.  Since RC2 was fairly widely used we want to preserve the files at approximately that point in time.  To make it a bit more clear what files are the point of this release, we do the following:

* rename the 'Previous Release' directories to 'Release'
* remove the 'Current Release' directories

Are there additional things to do here to make this more apparently an RC2 tree?

### CODE REVIEW

**Comment by aiaustin** [comment]
Whoops... a creating the request did not create the separate branch as I thought.

**Comment by aiaustin** [comment]
I messed that archive-rc2 branch creation up... a creating it merged it into master whereas I thought it would create the new branch. I reverted it so master is left unchanged but am not sure the best way to set up the branch and put in your contents Serie.

I would suggest you call the branch archive-ruth-rc2 by the way as rc2 will be ambiguous when we have a roth rc2.

I can see a way to allow all RuthandRoth members to have write access to the repositories of the group... but thats not what we want is it? But I cannot see where we give individuals like Serie and Sundance write/direct commit permission. Fred was going to read up on that this weekend.

**Comment by aiaustin** [comment]
Trying again after creating a branch called archive-ruth-rc2... which does seem to have worked.

I can see Serie's pull request showing as closed but still available via the pull request tab/closed link. But I cannot see a way now to reopen or merge Serie's commits into the new archive-ruth-rc2 branch.  In the spirit of learning while  the repository is still fresh I will continue to look at the instructions.  But if we can work out how to give nominated contributors write access that would be best.

**Comment by seriesumei** [comment]
I see the branch now, but it is of current master.  Can you branch at commit 8780455b46f3bcfe07018d0b2bdf7701b01db6e3 (Shin's last one)?

git checkout 8780455b46f3bcfe07018d0b2bdf7701b01db6e3
git push origin HEAD:archive-ruth-rc2

Then I can re-submit my PR

**Pull request merged**
